// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbIILiJNzmZZfO0RnR5ph9Cq8Dmc6UJvU',
    appId: '1:572317689764:web:0b76999d0f5d64d195c331',
    messagingSenderId: '572317689764',
    projectId: 'moodtracker-66c75',
    authDomain: 'moodtracker-66c75.firebaseapp.com',
    storageBucket: 'moodtracker-66c75.firebasestorage.app',
    measurementId: 'G-ZGHJ6VZ2EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycQMSc-33wFi1FbhZOVq7YfIFn5uMUI0',
    appId: '1:572317689764:android:f49c3cf477f3cd7495c331',
    messagingSenderId: '572317689764',
    projectId: 'moodtracker-66c75',
    storageBucket: 'moodtracker-66c75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKrd4pjvOo7ffgcs3DNALqIF1fERq68gg',
    appId: '1:572317689764:ios:dd1d812506bd3a5995c331',
    messagingSenderId: '572317689764',
    projectId: 'moodtracker-66c75',
    storageBucket: 'moodtracker-66c75.firebasestorage.app',
    iosBundleId: 'com.example.moodtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKrd4pjvOo7ffgcs3DNALqIF1fERq68gg',
    appId: '1:572317689764:ios:dd1d812506bd3a5995c331',
    messagingSenderId: '572317689764',
    projectId: 'moodtracker-66c75',
    storageBucket: 'moodtracker-66c75.firebasestorage.app',
    iosBundleId: 'com.example.moodtracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbIILiJNzmZZfO0RnR5ph9Cq8Dmc6UJvU',
    appId: '1:572317689764:web:5316ab97c04d3d7095c331',
    messagingSenderId: '572317689764',
    projectId: 'moodtracker-66c75',
    authDomain: 'moodtracker-66c75.firebaseapp.com',
    storageBucket: 'moodtracker-66c75.firebasestorage.app',
    measurementId: 'G-K2Q240HZ6G',
  );
}
